#!/bin/bash
set -e
# cd to self bash script directory
cd $( dirname ${BASH_SOURCE[0]})
echo Running isort
isort --profile black src
echo Running black
black src
echo Running ruff src
ruff check src
echo Running mypy src
mypy src
echo Linting complete!