#!/bin/bash
set -e
# cd to self bash script directory
cd $( dirname ${BASH_SOURCE[0]})
echo Running ruff format
uv run --group test ruff format src
echo Running ruff check
uv run --group test ruff check --fix src
echo Running pyright src
uv run --group test pyright src
echo Linting complete!
